name: minimal_design
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_database: ^11.0.0

dev_dependencies:
  flutter_lints: ^4.0.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/img_logo/
