// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-R55E5JXRysGZ9U3zZn2TBRZacCAS-SY',
    appId: '1:830745733362:web:b1665d918f9fd557c8c86b',
    messagingSenderId: '830745733362',
    projectId: 'loginstf-880c0',
    authDomain: 'loginstf-880c0.firebaseapp.com',
    storageBucket: 'loginstf-880c0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGkCAepmFCDO88S-O6v2rtVSBYd1NmddI',
    appId: '1:830745733362:android:5f622c1e11886a0bc8c86b',
    messagingSenderId: '830745733362',
    projectId: 'loginstf-880c0',
    storageBucket: 'loginstf-880c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkZXvlcCCWT-DchFUA6GKcg-NJGASZlf0',
    appId: '1:830745733362:ios:4e0278af3d136837c8c86b',
    messagingSenderId: '830745733362',
    projectId: 'loginstf-880c0',
    storageBucket: 'loginstf-880c0.appspot.com',
    iosBundleId: 'com.example.minimalDesign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkZXvlcCCWT-DchFUA6GKcg-NJGASZlf0',
    appId: '1:830745733362:ios:4e0278af3d136837c8c86b',
    messagingSenderId: '830745733362',
    projectId: 'loginstf-880c0',
    storageBucket: 'loginstf-880c0.appspot.com',
    iosBundleId: 'com.example.minimalDesign',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-R55E5JXRysGZ9U3zZn2TBRZacCAS-SY',
    appId: '1:830745733362:web:bf2611f7553f56b1c8c86b',
    messagingSenderId: '830745733362',
    projectId: 'loginstf-880c0',
    authDomain: 'loginstf-880c0.firebaseapp.com',
    storageBucket: 'loginstf-880c0.appspot.com',
  );

}